spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: http://localhost:1020
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=0
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
      disable-swagger-default-url: true

server:
  port: 1010

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"